/**
 * Reporting: PDF (pdfkit) and Excel (exceljs) export for a cycle.
 */
const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const { query, queryOne } = require('../config/db');
const { ApiError, asyncHandler } = require('../middleware/error');
const { writeAudit, clientIp } = require('../utils/audit');

async function fetchCycleData(cycleId) {
  const cycle = await queryOne('SELECT c.*, p.name AS project_name, p.code AS project_code FROM test_cycles c JOIN projects p ON p.id = c.project_id WHERE c.id = $1', [cycleId]);
  if (!cycle) throw ApiError.notFound('Cycle not found');
  const tests = await query(
    `SELECT ct.*, tc.code, tc.title, tc.module, tc.priority, u.full_name AS assignee_name,
            e.status AS last_status, e.execution_type
     FROM cycle_tests ct
     JOIN test_cases tc ON tc.id = ct.test_case_id
     LEFT JOIN users u ON u.id = ct.assignee_id
     LEFT JOIN v_latest_execution e ON e.cycle_test_id = ct.id
     WHERE ct.cycle_id = $1 ORDER BY tc.code`,
    [cycleId]
  );
  const stats = await queryOne(
    `SELECT count(*)::int AS total,
            count(*) FILTER (WHERE status = 'pending')::int AS pending,
            count(*) FILTER (WHERE status = 'in_progress')::int AS in_progress,
            count(*) FILTER (WHERE status = 'passed')::int AS passed,
            count(*) FILTER (WHERE status = 'failed')::int AS failed,
            count(*) FILTER (WHERE status = 'blocked')::int AS blocked,
            count(*) FILTER (WHERE status IN ('passed','failed','blocked'))::int AS executed
     FROM cycle_tests WHERE cycle_id = $1`,
    [cycleId]
  );
  const executions = await query(
    `SELECT e.*, tc.code, u.full_name AS executed_by_name FROM executions e
     JOIN test_cases tc ON tc.id = e.test_case_id LEFT JOIN users u ON u.id = e.executed_by
     WHERE e.cycle_id = $1 ORDER BY e.created_at DESC LIMIT 100`,
    [cycleId]
  );
  return { cycle, tests: tests.rows, stats, executions: executions.rows };
}

/** GET /api/reports/cycle/:id.pdf */
const pdf = asyncHandler(async (req, res) => {
  const { cycle, tests, stats } = await fetchCycleData(Number(req.params.id));

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="cycle-${cycle.id}-${cycle.name.replace(/[^a-z0-9]/gi,'_')}.pdf"`);

  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  doc.pipe(res);

  doc.fontSize(20).text(`Cycle Report: ${cycle.name}`, { align: 'left' });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#666').text(`Project: ${cycle.project_code} - ${cycle.project_name} | Cycle ID: ${cycle.id} | Generated: ${new Date().toISOString()}`);
  doc.moveDown();
  doc.fillColor('#000').fontSize(12).text(`Description: ${cycle.description || '—'}`);
  doc.moveDown();

  // Summary cards
  doc.fontSize(14).text('Summary', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(10).text(`Total: ${stats.total} | Executed: ${stats.executed} (${stats.total ? Math.round(stats.executed/stats.total*100) : 0}%) | Passed: ${stats.passed} | Failed: ${stats.failed} | Blocked: ${stats.blocked} | Pending: ${stats.pending} | In Progress: ${stats.in_progress}`);
  doc.moveDown();

  // Table header
  doc.fontSize(12).text('Test Cases', { underline: true });
  doc.moveDown(0.5);
  const tableTop = doc.y;
  const col = { code: 50, title: 110, module: 300, status: 380, assignee: 430, remarks: 480 };
  doc.fontSize(8).fillColor('#444');
  doc.text('Code', col.code, tableTop, { width: 60 });
  doc.text('Title', col.title, tableTop, { width: 180 });
  doc.text('Module', col.module, tableTop, { width: 70 });
  doc.text('Status', col.status, tableTop, { width: 50 });
  doc.text('Assignee', col.assignee, tableTop, { width: 80 });
  doc.moveDown();
  doc.fillColor('#000');
  let y = doc.y;
  for (const t of tests) {
    if (y > 750) { doc.addPage(); y = 50; }
    doc.fontSize(7);
    doc.text(t.code, col.code, y, { width: 60 });
    doc.text((t.title || '').slice(0, 80), col.title, y, { width: 180 });
    doc.text(t.module || '', col.module, y, { width: 70 });
    doc.text(t.status || '', col.status, y, { width: 50 });
    doc.text((t.assignee_name || '').slice(0, 20), col.assignee, y, { width: 80 });
    y += 14;
    if (y > 750) { doc.addPage(); y = 50; }
  }

  doc.moveDown(2);
  doc.fontSize(8).fillColor('#666').text(`Report generated by Test Trace & Automate • ${new Date().toISOString()}`, { align: 'center' });

  doc.end();

  await writeAudit({ userId: req.user.id, entityType: 'test_cycle', entityId: cycle.id, action: 'export_pdf', ip: clientIp(req) });
});

/** GET /api/reports/cycle/:id.xlsx */
const excel = asyncHandler(async (req, res) => {
  const { cycle, tests, stats, executions } = await fetchCycleData(Number(req.params.id));

  const wb = new ExcelJS.Workbook();
  wb.creator = 'Test Trace & Automate';
  wb.created = new Date();

  // Summary sheet
  const wsSummary = wb.addWorksheet('Summary');
  wsSummary.addRow(['Cycle Report', cycle.name]);
  wsSummary.addRow(['Project', `${cycle.project_code} - ${cycle.project_name}`]);
  wsSummary.addRow(['Cycle ID', cycle.id]);
  wsSummary.addRow(['Description', cycle.description || '']);
  wsSummary.addRow([]);
  wsSummary.addRow(['Metric', 'Value']);
  wsSummary.addRow(['Total', stats.total]);
  wsSummary.addRow(['Executed', stats.executed]);
  wsSummary.addRow(['Passed', stats.passed]);
  wsSummary.addRow(['Failed', stats.failed]);
  wsSummary.addRow(['Blocked', stats.blocked]);
  wsSummary.addRow(['Pending', stats.pending]);
  wsSummary.addRow(['In Progress', stats.in_progress]);
  wsSummary.getRow(1).font = { bold: true, size: 14 };

  // Detailed sheet
  const wsDetail = wb.addWorksheet('Test Cases');
  wsDetail.addRow(['Code', 'Title', 'Module', 'Priority', 'Status', 'Assignee', 'Due Date', 'Actual Result', 'Remarks']);
  wsDetail.getRow(1).font = { bold: true };
  for (const t of tests) {
    wsDetail.addRow([t.code, t.title, t.module, t.priority, t.status, t.assignee_name, t.due_date ? new Date(t.due_date).toISOString().slice(0,10) : '', t.actual_result || '', t.remarks || '']);
  }
  wsDetail.columns.forEach(col => { col.width = 20; });

  // Executions sheet
  const wsExec = wb.addWorksheet('Executions');
  wsExec.addRow(['Execution ID', 'Test Case', 'Status', 'Type', 'Actual Result', 'Executed By', 'Created At']);
  wsExec.getRow(1).font = { bold: true };
  for (const e of executions) {
    wsExec.addRow([e.id, e.code, e.status, e.execution_type, e.actual_result || '', e.executed_by_name || '', e.created_at]);
  }

  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.setHeader('Content-Disposition', `attachment; filename="cycle-${cycle.id}-${cycle.name.replace(/[^a-z0-9]/gi,'_')}.xlsx"`);

  await wb.xlsx.write(res);
  res.end();

  await writeAudit({ userId: req.user.id, entityType: 'test_cycle', entityId: cycle.id, action: 'export_excel', ip: clientIp(req) });
});

/** GET /api/reports/summary?projectId=&cycleId= */
const summary = asyncHandler(async (req, res) => {
  const { projectId, cycleId } = req.query;
  if (!cycleId && !projectId) throw ApiError.badRequest('projectId or cycleId required');
  const data = await fetchCycleData(Number(cycleId || 0)).catch(async () => {
    // if no cycleId, aggregate by project
    if (!projectId) throw ApiError.notFound('Cycle not found');
    const cycles = await query('SELECT id FROM test_cycles WHERE project_id = $1', [Number(projectId)]);
    const ids = cycles.rows.map(r => r.id);
    if (!ids.length) return { cycle: null, tests: [], stats: { total: 0 }, executions: [] };
    const stats = await queryOne(`SELECT count(*)::int AS total, count(*) FILTER (WHERE status='passed')::int AS passed, count(*) FILTER (WHERE status='failed')::int AS failed FROM cycle_tests WHERE cycle_id = ANY($1::int[])`, [ids]);
    return { cycle: { id: null, name: `Project ${projectId} summary` }, tests: [], stats, executions: [] };
  });
  res.json(data);
});

module.exports = { pdf, excel, summary };
